# These are supported funding model platforms

github: masterfermin02 # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: https://www.paypal.com/donate?hosted_button_id=DFLGVGVP593DA
